---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecars
  template:
    metadata:
      labels:
        app: sidecars
    spec:
      volumes:
        - name: fluentd-config-volume
          configMap:
            name: fluentd-config
      containers:
        - name: sidecars
          image: |
            {{.Values.sidecars.image.repository}}:{{.Values.sidecars.image.tag}}
          imagePullPolicy: "{ { .Values.sidecars.image.pullPolicy } }"
        - name: logger
          image: |
            {{.Values.logger.image.repository}}:{{.Values.logger.image.tag}}
          imagePullPolicy: "{ { .Values.logger.image.pullPolicy } }"
          volumeMounts:
            - name: fluentd-config-volume
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
